In [13]:
import cv2
import numpy as np

img = cv2.imread('musedash_final_Colored_Lines.png', cv2.IMREAD_UNCHANGED)

size=(10,10)
#size=(40,20)
#size=(80,40)
resized = cv2.resize(img, size, interpolation = cv2.INTER_AREA)
cv2.imwrite('resized_image.png',resized)

True

In [11]:
cap = cv2.VideoCapture('pred_video_compressed2.mp4')
frameCount = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
#frameWidth = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
#frameHeight = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

fc = 0
ret = True

buffer = []
while (fc < frameCount and ret):
    ret, frame = cap.read()
    buffer.append(cv2.resize(frame, size, interpolation = cv2.INTER_AREA))
    fc += 1

cap.release()

In [12]:
size=(10,10)
row = 0
current_LED = 0
for i in range(size[1]):
    for j in range(size[0]):
        print(current_LED)
        if (i % 2) == 0:
            print(frame[i,row+j])
        else:
            print(frame[i,size[0]+row-j-1])
        current_LED += 1
    row += size[0]

0
[143 144 139]
1
[143 144 139]
2
[143 144 139]
3
[143 144 139]
4
[143 144 139]
5
[143 144 139]
6
[143 144 139]
7
[143 144 139]
8
[143 144 139]
9
[143 144 139]
10
[146 147 142]
11
[145 146 141]
12
[145 146 141]
13
[145 146 141]
14
[144 145 140]
15
[144 145 140]
16
[143 144 139]
17
[143 144 139]
18
[143 144 139]
19
[143 144 139]
20
[146 147 142]
21
[146 147 142]
22
[146 147 142]
23
[146 147 142]
24
[146 147 142]
25
[146 147 142]
26
[146 147 142]
27
[146 147 142]
28
[146 147 142]
29
[146 147 142]
30
[146 147 142]
31
[146 147 142]
32
[146 147 142]
33
[146 147 142]
34
[146 147 142]
35
[146 147 142]
36
[146 147 142]
37
[146 147 142]
38
[146 147 142]
39
[146 147 142]
40
[146 147 142]
41
[146 147 142]
42
[146 147 142]
43
[146 147 142]
44
[147 148 143]
45
[147 148 143]
46
[147 148 143]
47
[149 150 145]
48
[149 150 145]
49
[149 150 145]
50
[150 152 145]
51
[149 151 144]
52
[149 151 144]
53
[149 151 144]
54
[149 150 145]
55
[149 150 145]
56
[149 150 145]
57
[149 150 145]
58
[149 150 145]
59
[149